### ISSUE TITLE
Finer face pixels

### ISSUE THREAD

**Issue by kantaiz3** [silveredgold/beta-censoring#11]
I'm not sure whether this is the right project to report, so sorry if I got this wrong 🤐

Even the finest pixel level (very light⁠—1) for faces is very blocky compared to Beta Safety. Having an option with pixels about half the current size would be nice.

**Comment by silveredgold** [comment]
I moved it here since (for now) it's exposed as an option only in the Beta Censoring server configuration. If I get more requests/feedback for this, I'll look at adding an option for it in Beta Protection's options.

--- 

For now, this option is available in the server configuration's `CensorOptions`, with the new `ClassStrength` key. For example, setting matches for the face to be half their current size would look like the following:

```json
  "CensorOptions": {
    "ClassStrength": {
      "FACE_F": 0.5
    }
  }
```

To use these options, you'll need to either use a CI build, or wait for v0.09

**Comment by kantaiz3** [comment]
Just tested it and it works flawlessly!! Thank you for implementing this ❤️
