### ISSUE TITLE
Stickers + pixels

### ISSUE THREAD

**Issue by kantaiz3** [silveredgold/beta-censoring#12]
Again, I'm not sure whether this is the right repo >w<

Stickers censoring blurs the image. It would be nice to have an option to pixelate it instead.

**Comment by silveredgold** [comment]
I moved it here since (for now) it's exposed as an option only in the Beta Censoring server configuration. Like your other request, if I get more requests/feedback for this, I'll look at adding an option for it in Beta Protection's options.

--- 

For now, this option is available in the server configuration's `CensorOptions`, with the new `ForcePixelBackground` key. For example, you could force stickers to use pixels instead of blurs with the following:

```json
  "CensorOptions": {
    "ForcePixelBackground": true
  }
```

To use these options, you'll need to either use a CI build, or wait for v0.09

**Comment by kantaiz3** [comment]
I just tested it and the pixels look really good. Thank you!!

---

Stickers are still somewhat... bugged. Some parts now have a pixelated (or blurred) background, but no sticker. All my stickers are either squares or landscape (so width > height). It seems like when the image being censored is a portrait (width < height) that no sticker is found.  At least, most of the time... it works for some.

It's not a big deal tho. I still get a censored images at the end of the day 😄

**Comment by silveredgold** [comment]
It's not based on the image's dimensions; it's based on the *match* dimensions. So, if the part of the image that needs censoring is "portrait" (i.e. `width < height`) and you don't have any stickers that are close enough to the aspect ratio of the area to be censored, it will indeed skip it since the server doesn't have an image that would fit in the area it needs to fill.

The more varied the dimensions of the stickers you have enabled, the more likely it is that the server can find one that will fit the area it needs to fill.

**Comment by CarmenRider** [comment]
I have mostly stickers that are transparent PNGs that are mostly square but have varied sizes. Yet somehow it's not picking a sticker, what do I do?
