### ISSUE TITLE
How to delete blur from sticker background ?

### ISSUE THREAD

**Issue by ShiranuiBigBoing** [silveredgold/beta-censoring#18]
Hi!I try to use sliders in "Censoring Options", but it had no effect. I am use BetaCensor.Server and nothing else.
And stickers doesn't work on Female eyes, only blur.
![Screenshot_7](https://user-images.githubusercontent.com/91887019/211906132-2eb243b6-1f93-4214-934c-2f03d0afd6e4.png)

**Comment by silveredgold** [comment]
For now, you can't delete the blur, you can choose either blurring or pixelation to be shown under the sticker, but there needs to be *something* under the sticker since the server can't guarantee the sticker will cover the whole matched area.

If you want pixels instead of blurs, you can set the `ForcePixelBackground` option in your config file (something like below): 

```json
"CensorOptions": {
    "ForcePixelBackground": true
  }
```

**Comment by ShiranuiBigBoing** [comment]
Thank you very much it works
